<?php
    $order = new Mage_Sales_Model_Order();
    $orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
    $order->loadByIncrementId($orderId);
?>

<h2><?php echo $this->__('Compra Realizada com Sucesso!') ?></h2>

<h3>Seu pedido foi registrado.</h3>

<form name="modulopagamento" method="post" action="<?php echo Mage::helper('modulopagamento')->recuperarGatewayPagamentoUrl(); ?>">
    <input type="hidden" name="orderId" value="<?php echo $orderId; ?>">
    <input type="submit" value="<?php echo $this->__('Detalhes do Pedido') ?>" />
</form>